services:
  node:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app      docker exec -it <node_container_name> node --version
    command: tail -f /dev/null # Keeps container running for development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: skillara_dev
      POSTGRES_USER: skillara_user
      POSTGRES_PASSWORD: your_secure_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: