version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: skillara-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: skillara_dev
      POSTGRES_USER: skillara_user
      POSTGRES_PASSWORD: skillara_dev_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d:ro
      - ./database/seeds:/seeds:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U skillara_user -d skillara_dev"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: skillara-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: skillara-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@skillara.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    name: skillara_postgres_data
  redis_data:
    name: skillara_redis_data
  pgadmin_data:
    name: skillara_pgadmin_data

networks:
  default:
    name: skillara_network
