services:
  node:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    command: tail -f /dev/null # Keeps container running for development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: skillara_dev
      POSTGRES_USER: skillara_user
      POSTGRES_PASSWORD: skillara_dev_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U skillara_user -d skillara_dev"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pgdata:
  redisdata: