export declare const API_ENDPOINTS: {
    readonly CAREER_ANALYSIS: "/api/career-analysis";
    readonly SKILL_GAP_ANALYSIS: "/api/career-analysis/skill-gaps";
    readonly LEARNING_PATH: "/api/career-analysis/learning-path";
    readonly MARKET_POSITION: "/api/career-analysis/market-position";
    readonly DOCUMENT_PROCESSING: "/api/document-processing";
    readonly DOCUMENT_UPLOAD: "/api/document-processing/upload";
    readonly DOCUMENT_ANALYZE: "/api/document-processing/analyze";
    readonly SKILL_EXTRACTION: "/api/document-processing/extract-skills";
    readonly JOB_MARKET: "/api/job-market";
    readonly JOB_ROLES: "/api/job-market/roles";
    readonly SALARY_BENCHMARKS: "/api/job-market/salary-benchmarks";
    readonly SKILL_DEMAND: "/api/job-market/skill-demand";
    readonly LEARNING_RECOMMENDATIONS: "/api/learning-recommendations";
    readonly LEARNING_RESOURCES: "/api/learning-recommendations/resources";
    readonly SKILL_DEVELOPMENT_PLANS: "/api/learning-recommendations/development-plans";
    readonly SESSIONS: "/api/sessions";
    readonly SESSION_CREATE: "/api/sessions/create";
    readonly SESSION_VALIDATE: "/api/sessions/validate";
    readonly SESSION_EXTEND: "/api/sessions/extend";
    readonly ANALYTICS: "/api/analytics";
    readonly ANALYTICS_EVENTS: "/api/analytics/events";
    readonly ANALYTICS_METRICS: "/api/analytics/metrics";
    readonly HEALTH: "/health";
    readonly STATUS: "/status";
    readonly METRICS: "/metrics";
};
export declare const ERROR_CODES: {
    readonly INTERNAL_ERROR: "INTERNAL_ERROR";
    readonly VALIDATION_ERROR: "VALIDATION_ERROR";
    readonly NOT_FOUND: "NOT_FOUND";
    readonly UNAUTHORIZED: "UNAUTHORIZED";
    readonly FORBIDDEN: "FORBIDDEN";
    readonly RATE_LIMITED: "RATE_LIMITED";
    readonly SESSION_EXPIRED: "SESSION_EXPIRED";
    readonly SESSION_INVALID: "SESSION_INVALID";
    readonly SESSION_NOT_FOUND: "SESSION_NOT_FOUND";
    readonly DOCUMENT_TOO_LARGE: "DOCUMENT_TOO_LARGE";
    readonly DOCUMENT_INVALID_FORMAT: "DOCUMENT_INVALID_FORMAT";
    readonly DOCUMENT_PROCESSING_FAILED: "DOCUMENT_PROCESSING_FAILED";
    readonly DOCUMENT_CORRUPTED: "DOCUMENT_CORRUPTED";
    readonly AI_SERVICE_UNAVAILABLE: "AI_SERVICE_UNAVAILABLE";
    readonly AI_RATE_LIMIT_EXCEEDED: "AI_RATE_LIMIT_EXCEEDED";
    readonly AI_PROCESSING_FAILED: "AI_PROCESSING_FAILED";
    readonly DATABASE_CONNECTION_FAILED: "DATABASE_CONNECTION_FAILED";
    readonly DATABASE_QUERY_FAILED: "DATABASE_QUERY_FAILED";
    readonly DATABASE_CONSTRAINT_VIOLATION: "DATABASE_CONSTRAINT_VIOLATION";
    readonly EXTERNAL_SERVICE_UNAVAILABLE: "EXTERNAL_SERVICE_UNAVAILABLE";
    readonly EXTERNAL_SERVICE_TIMEOUT: "EXTERNAL_SERVICE_TIMEOUT";
};
export declare const BUSINESS_RULES: {
    readonly MAX_FILE_SIZE_MB: 10;
    readonly ALLOWED_FILE_TYPES: readonly ["pdf", "doc", "docx", "txt"];
    readonly DEFAULT_SESSION_DURATION_HOURS: 24;
    readonly MAX_SESSION_DURATION_HOURS: 168;
    readonly SESSION_CLEANUP_INTERVAL_HOURS: 6;
    readonly MIN_CONFIDENCE_SCORE: 0.3;
    readonly MAX_SKILLS_PER_PROFILE: 50;
    readonly MIN_PROFICIENCY_LEVEL: 1;
    readonly MAX_PROFICIENCY_LEVEL: 4;
    readonly MAX_LEARNING_OBJECTIVES: 10;
    readonly MAX_RESOURCES_PER_SKILL: 5;
    readonly MIN_LEARNING_DIFFICULTY: 1;
    readonly MAX_LEARNING_DIFFICULTY: 5;
    readonly API_RATE_LIMIT_PER_MINUTE: 60;
    readonly UPLOAD_RATE_LIMIT_PER_MINUTE: 5;
    readonly AI_REQUESTS_PER_HOUR: 100;
    readonly ANONYMOUS_DATA_RETENTION_DAYS: 30;
    readonly ERROR_LOG_RETENTION_DAYS: 90;
    readonly ANALYTICS_DATA_RETENTION_DAYS: 365;
};
